---
- name: validation | Check connectivity for FBServer
  shell: ping -q -c 4 -W 1 {{ fb_vars.fb_host }}
  register: fb_ping_status
  failed_when: false
  changed_when: false

- name: validation | Fail if Flashblade server not reachable
  fail:
    msg: FB server {{ fb_vars.fb_host }} not reachable
  when: "'100% packet loss' in fb_ping_status.stdout"

- name: validation | Check if reachable fb_host is FB server or not to fail fast
  uri:
    url: https://{{ fb_vars.fb_host }}/api/api_version
    method: GET
    validate_certs: no
    return_content: yes
    timeout: 10
  register: api_version
  failed_when: false

- name: validation | Fail if "fb_host" is not FlashBlade server
  fail:
    msg: fb_host {{ fb_vars.fb_host }} is not a valid FlashBlade
  when: (api_version.status != 200 )

- name: policy | Create a filesystem snapshot policy on {{ outer_loop.key }}
  purefb_policy:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled | default('True') }}"
    at: "{{ item.at | default(omit)}}"
    keep_for: "{{ item.keep_for | default(omit)}}"
    every: "{{ item.every | default(omit) }}"
    timezone: "{{ item.timezone | default(omit) }}"
    state: "{{ 'absent' if item.state is defined and item.state == 'disabled' else 'present' }}"
    filesystem: "{{ item.filesystem | default(omit) }}"
    replica_link:  "{{ replica_link | default(omit) }}"
    fb_url: "{{ fb_vars.fb_host }}"
    api_token: "{{ fb_vars.api_token }}"
  loop: "{{ fb_vars.filesystem_snapshot_policy|default([]) }}"
  when:
    - item is defined and (item|default([])|length > 0)

- name: filesystem | Provision file system on {{ outer_loop.key }}
  purefb_fs:
    name: "{{ item.name }}"
    size: "{{ item.size | default(omit) }}"
    nfsv3: "{{ 'nfsv3' in item.type | default(omit)}}"
    nfsv4: "{{ 'nfsv4.1' in item.type | default(omit) }}"
    user_quota: "{{ item.user_quota | default(omit) }}"
    group_quota: "{{ item.group_quota | default(omit) }}"
    nfs_rules: "{{ item.nfs_rules | default(omit) }}"
    snapshot: "{{ item.snapshot | default('false') }}"
    fastremove: "{{ item.fastremove | default('false') }}"
    hard_limit: "{{ item.hard_limit | default('false') }}"
    smb: "{{ 'smb' in item.type | default(omit) }}"
    smb_aclmode: "{{ item.smb_aclmode | default(omit) }}"
    writable: "{{ item.writable | default(omit) }}"
    http: "{{ item.http | default(omit) }}"
    eradicate: "{{ item.eradicate | default('false') }}"
    promote: "{{ item.promote | default(omit) }}"
    state: "{{ 'absent' if item.state is defined and item.state == 'disabled' else 'present' }}"
    policy: "{{ item.policy | default(omit) }}"
    policy_state: "{{ item.policy_state | default(omit) }}"
    fb_url: "{{ fb_vars.fb_host }}"
    api_token: "{{ fb_vars.api_token }}"
  loop: "{{ fb_vars.filesystem | default([]) }}"
  when:
    - item is defined and (item|default([])|length > 0)
    - item.count is not defined or item.count == 0

- name: filesystem | Include task to setup multiple filesystem if count defined on {{ outer_loop.key }}
  include: filesystem_multi.yml
  loop: "{{ fb_vars.filesystem|default([]) }}"
  loop_control:
    loop_var: fs_loop
  when:
    - fs_loop is defined and (fs_loop|default([])|length > 0)
    - fs_loop.count is defined and fs_loop.count > 0

- name: snapshot | Create a filesystem snapshot on {{ outer_loop.key }}
  purefb_snap:
    name: "{{ item.filesystem_name }}"
    suffix: "{{ item.suffix }}"
    state: "{{ 'absent' if item.state is defined and item.state == 'disabled' else 'present' }}"
    eradicate: "{{ item.eradicate | default('false') }}"
    fb_url: "{{ fb_vars.fb_host }}"
    api_token: "{{ fb_vars.api_token }}"
  loop: "{{ fb_vars.filesystem_snapshot|default([]) }}"
  when:
    - item is defined and (item|default([])|length > 0)
    - item.restore_fs_from_snap is not defined or not item.restore_fs_from_snap|bool 
    - item.count is not defined or item.count == 0

- name: filesystem | Include task to create snapshot for multiple filesystem if count defined on {{ outer_loop.key }}
  include: snap_multi.yml
  loop: "{{ fb_vars.filesystem_snapshot|default([]) }}"
  loop_control:
    loop_var: snap_loop
  when:
    - snap_loop is defined and (snap_loop|default([])|length > 0)
    - item.restore_fs_from_snap is not defined or not item.restore_fs_from_snap|bool
    - snap_loop.count is defined and snap_loop.count > 0

- name: snapshot | Restore filesystem from snapshot on {{ outer_loop.key }}
  purefb_snap:
    name: "{{ item.filesystem_name }}"
    suffix: "{{ item.suffix }}"
    state: restore
    eradicate: "{{ item.eradicate | default('false') }}"
    fb_url: "{{ fb_vars.fb_host }}"
    api_token: "{{ fb_vars.api_token }}"
  loop: "{{ fb_vars.filesystem_snapshot|default([]) }}"
  when:
    - item is defined and (item|default([])|length > 0)
    - item.restore_fs_from_snap is defined and item.restore_fs_from_snap|bool
    - item.count is not defined or item.count == 0

- name: filesystem | Include task to restore multiple filesystems if count defined on {{ outer_loop.key }}
  include: snap_restore_multi.yml
  loop: "{{ fb_vars.filesystem_snapshot|default([]) }}"
  loop_control:
    loop_var: restore_loop
  when:
    - restore_loop is defined and (restore_loop|default([])|length > 0)
    - restore_loop.restore_fs_from_snap is defined and restore_loop.restore_fs_from_snap|bool
    - restore_loop.count is defined and restore_loop.count > 0
