---
- name: Update and install nfs-utils
  become: true
  when: ansible_os_family == "RedHat"
  block:
    - name: Install updates using yum
      ansible.builtin.yum:
        name: "*"
        state: latest
        only_upgrade: true
      failed_when: false

    - name: Packages | Install nfs packages on CentOS
      ansible.builtin.yum:
        name:
          - nfs-utils
          - nfs4-acl-tools
        state: latest
        only_upgrade: true

- name: Update and install nfs-common package
  become: true
  when: ansible_os_family == "Debian"
  block:
    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      failed_when: false

    - name: Packages | Install nfs packages on Ubuntu
      ansible.builtin.apt:
        name:
          - nfs-common
          - nfs4-acl-tools
        state: latest
        only_upgrade: true
