---
- name: filesystem | Provision multiple file system on {{ outer_loop.key }}
  purefb_fs:
    name: "{{ item }}"
    size: "{{ fs_loop.size | default(omit) }}"
    nfsv3: "{{ 'nfsv3' in fs_loop.type | default(omit)}}"
    nfsv4: "{{ 'nfsv4.1' in fs_loop.type | default(omit) }}"
    user_quota: "{{ fs_loop.user_quota | default(omit) }}"
    group_quota: "{{ fs_loop.group_quota | default(omit) }}"
    nfs_rules: "{{ fs_loop.nfs_rules | default(omit) }}"
    snapshot: "{{ fs_loop.snapshot | default('false') }}"
    fastremove: "{{ fs_loop.fastremove | default('false') }}"
    hard_limit: "{{ fs_loop.hard_limit | default('false') }}"
    smb: "{{ 'smb' in fs_loop.type | default(omit) }}"
    smb_aclmode: "{{ fs_loop.smb_aclmode | default(omit) }}"
    writable: "{{ fs_loop.writable | default(omit) }}"
    http: "{{ fs_loop.http | default(omit) }}"
    policy: "{{ fs_loop.policy | default(omit) }}"
    policy_state: "{{ fs_loop.policy_state | default(omit) }}"
    eradicate: "{{ fs_loop.eradicate | default('false') }}"
    promote: "{{ fs_loop.eradicate | default('true') }}"
    state: "{{ 'absent' if fs_loop.state is defined and fs_loop.destroy | bool else 'present' }}"
    fb_url: "{{ fb_vars.fb_host }}"
    api_token: "{{ fb_vars.api_token }}"
  with_sequence: start=1 end="{{ fs_loop.count }}" format="{{ fs_loop.name }}_%02d"
