---
# Map of Kubernetes minor version to RKE Kubernetes version
kubernetes_supported_versions:
  "1.18": v1.18.6-rancher1-1
  "1.17": v1.17.9-rancher1-1
  "1.16": v1.16.13-rancher1-1
  "1.15": v1.15.12-rancher2-4

# Default Kubernetes minor version
kubernetes_version: "1.18"

rke_release: v1.1.4
rke_binary_url: "https://github.com/rancher/rke/releases/download/{{ rke_release }}/rke_linux-amd64"
rke_binary_checksum: sha256:1c7bb6e7eb3c820475b3ecbc4fc5786a912658b9d0e1f4323759c1bb72d6a758
rke_kubernetes_version: "{{ kubernetes_supported_versions[kubernetes_version] }}"

rke_config_dir: "{{ ansible_env.HOME | default(ansible_env.PWD) | default('/root') }}/rancher"
rke_force_configure: true

rke_ssh_user: centos
rke_node_roles: [controlplane, worker, etcd]
