---
- name: Update and install nfs-utils
  block:
  - name: install updates using yum
    yum:
      name: "*"
      state: latest
      skip_broken: yes
    ignore_errors: true

  - name: packages | Install nfs packages on CentOS
    yum:
      name: 
        - nfs-utils
        #- nfs4-acl-tools
      state: latest
  become: yes
  when: ansible_os_family == "RedHat"

- name: Update and install nfs-common package
  block:
  - name: Update apt packages
    apt:
      update_cache: yes
      cache_valid_time: 3600
    ignore_errors: true

  - name: packages | Install nfs packages on Ubuntu
    apt:
      name: 
        - nfs-common
        #- nfs4-acl-tools
      state: latest
  become: yes
  when: ansible_os_family == "Debian"
